#include <Camelino.h>

#define SENSOR_PIN A0

// TODO: replace with camelino-embed generated bytecode.h
static const uint8_t sensor_bytecode[] = {};

void setup() {
  Camelino_begin();
}

void loop() {
  (void)SENSOR_PIN;
  Camelino_execute_bytes(sensor_bytecode, sizeof(sensor_bytecode));
  delay(500);
}
