#!/bin/bash
# ================================================================
# camelino-stub — C Stub 集成工具 (Phase 6.9)
# ================================================================
# 将 OCaml 外部 C stub 文件集成到 Camelino 设备端固件中。
#
# 用法:
#   camelino-stub scan   <stub.c>                    — 列出 C stub 中的 caml_* 符号
#   camelino-stub wrap   <stub.c> [-o wrapper.h]     — 生成 Arduino 兼容的 wrapper
#   camelino-stub embed  <stub.c> --bytecode <file>   — 完整集成: stub + bytecode
#
# 工作流:
#   1. ocamlc -custom -o prog prog.cmo stub.o   (PC 端自定义链接)
#   2. camelino-stub wrap stub.c -o camelino_stubs.h
#   3. #include "camelino_stubs.h" 在 .ino 文件中
#   4. 编译 + 烧录
# ================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---- 列出 C stub 中的 caml_* 符号 ----
cmd_scan() {
    local stub="$1"
    if [ ! -f "$stub" ]; then
        echo "Error: file not found: $stub"
        exit 1
    fi
    echo "=== C Stub Symbols in $(basename "$stub") ==="
    echo ""
    echo "  Primitive functions (CAMLprim / CAMLexport):"
    grep -n "CAMLprim\|CAMLexport\|^value caml_\|^CAMLprim value" "$stub" | while read line; do
        echo "    $line"
    done
    echo ""
    echo "  Registered primitive names (caml_register_*):"
    grep -n "caml_register" "$stub" | while read line; do
        echo "    $line"
    done

    # Extract symbol names for the Camelino primitive table
    echo ""
    echo "  Symbols to register:"
    grep -oE '"caml_[^"]*"' "$stub" | sort -u | while read sym; do
        echo "    $sym"
    done
    echo ""
}

# ---- 生成 Arduino 兼容的 wrapper ----
cmd_wrap() {
    local stub=""
    local output="camelino_stubs.h"

    while [ $# -gt 0 ]; do
        case "$1" in
            -o) output="$2"; shift 2 ;;
            *)  stub="$1"; shift ;;
        esac
    done

    if [ ! -f "$stub" ]; then
        echo "Error: file not found: $stub"
        exit 1
    fi

    local basename=$(basename "$stub" .c)

    cat > "$output" << EOF
/**
 * @file $output
 * @brief Auto-generated Camelino C Stub Wrapper (Phase 6.9)
 *
 * Generated from: $stub
 * Generated by:  camelino-stub wrap
 *
 * Include this file in your Arduino sketch to register the C primitives
 * that the OCaml bytecode expects.
 */

#ifndef CAMELINO_STUBS_H
#define CAMELINO_STUBS_H

#ifdef __cplusplus
extern "C" {
#endif

/* ---- C Stub Source (inlined for Arduino single-TU compilation) ---- */

EOF

    # Include the stub source directly (Arduino compiles as single translation unit)
    echo "/* === Begin $basename.c === */" >> "$output"
    cat "$stub" >> "$output"
    echo "/* === End $basename.c === */" >> "$output"

    # Extract primitive names from register calls
    local prims=$(grep -oE '"caml_[^"]*"' "$stub" 2>/dev/null | sort -u | tr '\n' ' ')

    cat >> "$output" << EOF

/* ---- Auto-registration ---- */

/**
 * Register all C primitives from this stub.
 * Call this ONCE after caml_init_primitives().
 */
static inline void camelino_register_stub_primitives(void) {
EOF

    for prim in $prims; do
        # Strip quotes
        prim=$(echo "$prim" | tr -d '"')
        # Generate a registration call for each primitive
        echo "    caml_register_global_primitive($prim, ${prim}_stub, 0); /* adjust arity */" >> "$output"
    done

    cat >> "$output" << EOF
}

#ifdef __cplusplus
}
#endif

#endif /* CAMELINO_STUBS_H */
EOF

    echo "Generated: $output"
    echo "  Stub source: $stub"
    echo "  Primitives:  $prims"
    echo ""
    echo "Usage in .ino file:"
    echo "  #include \"camelino_stubs.h\""
    echo "  // In setup():"
    echo "  camelino_register_stub_primitives();"
}

# ---- 完整嵌入: stub + bytecode ----
cmd_embed() {
    local stub=""
    local bytecode=""
    local output="camelino_embed.h"

    while [ $# -gt 0 ]; do
        case "$1" in
            --bytecode) bytecode="$2"; shift 2 ;;
            -o) output="$2"; shift 2 ;;
            *) stub="$1"; shift ;;
        esac
    done

    if [ -z "$stub" ] || [ -z "$bytecode" ]; then
        echo "Usage: camelino-stub embed <stub.c> --bytecode <file.camel> [-o output.h]"
        exit 1
    fi

    cat > "$output" << EOF
/**
 * @file $output
 * @brief Camelino Embedded Application Bundle (Phase 6.9)
 *
 * Contains: bytecode + C stubs — ready for Arduino inclusion.
 */

#ifndef CAMELINO_EMBED_H
#define CAMELINO_EMBED_H

/* === Bytecode (from $bytecode) === */
EOF

    # Embed bytecode as C array
    xxd -i "$bytecode" | sed 's/unsigned char/static const uint8_t/' >> "$output"

    cat >> "$output" << EOF

/* === C Stubs (from $stub) === */
EOF

    cat "$stub" >> "$output"

    cat >> "$output" << EOF

#endif /* CAMELINO_EMBED_H */
EOF

    echo "Generated: $output"
    echo "  Bytecode: $(wc -c < "$bytecode") bytes"
    echo "  Stub:     $stub"
}

# ---- Main ----
case "${1:-}" in
    scan)
        shift
        cmd_scan "$@"
        ;;
    wrap)
        shift
        cmd_wrap "$@"
        ;;
    embed)
        shift
        cmd_embed "$@"
        ;;
    *)
        echo "Camelino C Stub Integration Tool (Phase 6.9)"
        echo ""
        echo "Usage:"
        echo "  camelino-stub scan  <stub.c>                     List caml_* symbols"
        echo "  camelino-stub wrap  <stub.c> [-o wrapper.h]      Generate Arduino wrapper"
        echo "  camelino-stub embed <stub.c> --bytecode <f.camel> Full bundle"
        echo ""
        echo "Workflow:"
        echo "  1. Write OCaml program with 'external' declarations"
        echo "  2. Write C stub implementing the primitives"
        echo "  3. ocamlc -custom -o prog prog.cmo stub.o"
        echo "  4. camelino-stub wrap stub.c -o stubs.h"
        echo "  5. #include \"stubs.h\" in your .ino file"
        echo "  6. Upload to device"
        exit 1
        ;;
esac
