#!/bin/bash
# ================================================================
# camelino deploy — One-command build & flash for Camelino projects
# ================================================================
# Usage:
#   camelino deploy [options] <input.ml>
#
# Options:
#   --board NAME       Target board (default: rpipico2)
#   --platform NAME    Target platform: arduino, picosdk (default: arduino)
#   --port DEV         Serial port for upload (default: auto-detect)
#   --heap SIZE        Heap size in KB (default: 192k)
#   --no-upload        Build only, skip upload
#   --check            Run camelino-check before deploy
#   --clean            Clean OCaml intermediate files
#
# Examples:
#   camelino deploy blink.ml
#   camelino deploy --board rpipico2 --port /dev/ttyACM0 blink.ml
#   camelino deploy --platform picosdk --no-upload sensor.ml
# ================================================================
set -e

# ---- Defaults ----
BOARD="rpipico2"
PLATFORM="arduino"
PORT=""
HEAP="192k"
NO_UPLOAD=0
RUN_CHECK=0
DO_CLEAN=0
INPUT_ML=""

# ---- Paths ----
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLS_DIR="$PROJECT_ROOT/tools"
EMBED="$TOOLS_DIR/camelino-embed/camelino-embed"
CHECK="$TOOLS_DIR/camelino-check/_build/default/main.exe"
TEMP_DIR="/tmp/camelino_deploy_$$"

# ---- Parse args ----
while [ $# -gt 0 ]; do
    case "$1" in
        --board)   BOARD="$2"; shift 2 ;;
        --platform) PLATFORM="$2"; shift 2 ;;
        --port)    PORT="$2"; shift 2 ;;
        --heap)    HEAP="$2"; shift 2 ;;
        --no-upload) NO_UPLOAD=1; shift ;;
        --check)   RUN_CHECK=1; shift ;;
        --clean)   DO_CLEAN=1; shift ;;
        -*) echo "Unknown option: $1"; exit 1 ;;
        *)  INPUT_ML="$1"; shift ;;
    esac
done

if [ -z "$INPUT_ML" ]; then
    echo "Usage: camelino deploy [options] <input.ml>"
    echo ""
    echo "Options:"
    echo "  --board NAME     Target board (default: rpipico2)"
    echo "  --platform NAME  Target platform: arduino, picosdk (default: arduino)"
    echo "  --port DEV       Serial port for upload"
    echo "  --heap SIZE      Heap size (default: 192k)"
    echo "  --no-upload      Build only, skip flash"
    echo "  --check          Run camelino-check before deploy"
    echo "  --clean          Clean intermediate files"
    exit 1
fi

if [ ! -f "$INPUT_ML" ]; then
    echo "Error: file not found: $INPUT_ML"
    exit 1
fi

BASENAME="$(basename "$INPUT_ML" .ml)"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Camelino Deploy — $BASENAME"
echo "║  Platform: $PLATFORM  Board: $BOARD  Heap: $HEAP"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ---- Step 0: Build tools if needed ----
if [ ! -f "$EMBED" ]; then
    echo "[0/4] Building camelino-embed..."
    cd "$TOOLS_DIR/camelino-embed"
    ocamlfind ocamlc -linkpkg -package compiler-libs.common -o camelino-embed main.ml 2>/dev/null
    cd "$PROJECT_ROOT"
fi

# ---- Step 1: OCaml compile + embed ----
echo "[1/4] Compiling OCaml → bytecode..."
mkdir -p "$TEMP_DIR"

# Compile .ml → .cmo
ocamlc -c -o "$TEMP_DIR/$BASENAME.cmo" "$INPUT_ML" 2>&1 | tail -1

# Optional: ocamlclean (if available)
if command -v ocamlclean &>/dev/null; then
    ocamlclean "$TEMP_DIR/$BASENAME.cmo" -o "$TEMP_DIR/${BASENAME}_clean.cmo" 2>/dev/null || true
    [ -f "$TEMP_DIR/${BASENAME}_clean.cmo" ] && mv "$TEMP_DIR/${BASENAME}_clean.cmo" "$TEMP_DIR/$BASENAME.cmo"
fi

# Embed .cmo → .camel (intermediate) + bytecode.h
"$EMBED" "$TEMP_DIR/$BASENAME.cmo" -o "$TEMP_DIR/$BASENAME.camel" 2>&1 | tail -1

# Generate bytecode.h for Arduino embedding
"$EMBED" "$TEMP_DIR/$BASENAME.cmo" -o "$TEMP_DIR/bytecode.h" 2>/dev/null || true

BYTECODE_SIZE=$(wc -c < "$TEMP_DIR/$BASENAME.camel")
echo "  Bytecode: $BYTECODE_SIZE bytes"
echo ""

# ---- Step 2: camelino-check (optional) ----
if [ $RUN_CHECK -eq 1 ] && [ -f "$CHECK" ]; then
    echo "[2/4] Running camelino-check..."
    "$CHECK" "$TEMP_DIR/$BASENAME.cmo" --heap "$HEAP" --word-size 32 --platform "$PLATFORM" 2>&1
    echo ""
else
    echo "[2/4] camelino-check: skipped (use --check to enable)"
    echo ""
fi

# ---- Step 3: Platform compile ----
echo "[3/4] Compiling for $PLATFORM ($BOARD)..."

case "$PLATFORM" in
    arduino)
        # Arduino CLI compile
        if command -v arduino-cli &>/dev/null; then
            PORT_ARG=""
            [ -n "$PORT" ] && PORT_ARG="--port $PORT"
            arduino-cli compile --fqbn "arduino:mbed_rp2040:$BOARD" \
                --build-path "$TEMP_DIR/build" \
                "$PROJECT_ROOT/examples/Blink" 2>&1 | tail -3
        else
            echo "  arduino-cli not found — skipping platform compile"
            echo "  Install: brew install arduino-cli"
            echo "  Generated bytecode.h is at: $TEMP_DIR/bytecode.h"
        fi
        ;;
    picosdk)
        echo "  Pico SDK: use CMake to build"
        echo "  Generated .camel file is at: $TEMP_DIR/$BASENAME.camel"
        ;;
    *)
        echo "  Unknown platform: $PLATFORM"
        ;;
esac
echo ""

# ---- Step 4: Upload ----
if [ $NO_UPLOAD -eq 0 ]; then
    echo "[4/4] Uploading to device..."
    case "$PLATFORM" in
        arduino)
            if command -v arduino-cli &>/dev/null; then
                PORT_ARG=""
                [ -n "$PORT" ] && PORT_ARG="--port $PORT"
                arduino-cli upload --fqbn "arduino:mbed_rp2040:$BOARD" \
                    --input-dir "$TEMP_DIR/build" $PORT_ARG 2>&1 | tail -3
            else
                echo "  arduino-cli not found — cannot upload"
                echo "  Manual upload: copy bytecode.h to Arduino sketch and flash"
            fi
            ;;
        picosdk)
            echo "  Pico SDK: use picotool to flash"
            echo "  picotool load $TEMP_DIR/$BASENAME.uf2"
            ;;
    esac
else
    echo "[4/4] Upload: skipped (--no-upload)"
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Output: $TEMP_DIR/$BASENAME.camel ($BYTECODE_SIZE bytes)"
echo "  bytecode.h: $TEMP_DIR/bytecode.h"
echo "═══════════════════════════════════════════════════════════"

# Cleanup temp unless --clean wasn't requested (keep for inspection)
if [ $DO_CLEAN -eq 1 ]; then
    rm -rf "$TEMP_DIR"
    echo "  (temp files cleaned)"
else
    echo "  Temp files kept at: $TEMP_DIR"
fi
